project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "posts/**/*.qmd"

website:
  title: "Screeching Into The Void"
  site-url: "https://screechingintothevoid.com"
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
  page-footer:
    center: "© 2026 Ishaat Chowdhury"
    right:
      - icon: github
        href: https://github.com/ishchow/screechingintothevoid.com
        aria-label: Source Code

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
